// src/data.js
export const categories = ["Potato", "Tomato", "Coffee", "Cheese"];

export const stores = [
  {
    id: 1,
    name: "Laha Store",
    verified: true,
    distance: "1 km",
    address: "Tal ul chepk, Sodar Bazar, Dehradun",
    items: [
      {
        id: 101,
        name: "Potato",
        price: 18,
        unit: "kg",
        minQty: 10,
        bulkQty: 50,
        delivery: "All India Delivery",
        description: "Premium A-grade potatoes, freshly harvested.",
        rating: 4.9,
        reviews: "100K+",
      },
    ],
  },
  {
    id: 2,
    name: "GreenMart",
    verified: false,
    distance: "2.3 km",
    address: "Rajpur Road, Dehradun",
    items: [
      {
        id: 102,
        name: "Tomato",
        price: 30,
        unit: "kg",
        minQty: 5,
        bulkQty: 25,
        delivery: "Same-day delivery",
        description: "Farm-fresh organic tomatoes.",
        rating: 4.7,
        reviews: "12K",
      },
      {
        id: 103,
        name: "Cheese",
        price: 280,
        unit: "200g",
        minQty: 1,
        bulkQty: 10,
        delivery: "All India Delivery",
        description: "Cheddar cheese block.",
        rating: 4.8,
        reviews: "8K",
      },
    ],
  },
  {
    id: 3,
    name: "Daily Needs",
    verified: true,
    distance: "0.8 km",
    address: "Chakrata Road, Dehradun",
    items: [
      {
        id: 104,
        name: "Potato",
        price: 20,
        unit: "kg",
        minQty: 1,
        bulkQty: 50,
        delivery: "Free above ₹199",
        description: "Locally sourced.",
        rating: 4.6,
        reviews: "25K",
      },
      {
        id: 105,
        name: "Coffee",
        price: 250,
        unit: "500g",
        minQty: 1,
        bulkQty: 6,
        delivery: "All India Delivery",
        description: "Arabica roast beans.",
        rating: 4.7,
        reviews: "15K",
      },
    ],
  },
];